const clubLogoCodeMap: { [key: string]: string } = {
    // 'Juventus FC': 'https://brandlogos.net/wp-content/uploads/2017/01/juventus_FC-brandlogo.net_-300x300.png',
    // 'AC Milan': 'https://brandlogos.net/wp-content/uploads/2021/05/ac_milan-logo_brandlogos.net_xh3sl-300x485.png',
    // 'ACF Fiorentina': 'https://brandlogos.net/wp-content/uploads/2012/10/fiorentina-logo-vector.png',
    // 'AC Monza': 'https://brandlogos.net/wp-content/uploads/2022/08/ac_monza-logo_brandlogos.net_ymngy.png',
    // 'AS Roma': 'https://brandlogos.net/wp-content/uploads/2024/04/as_roma-logo_brandlogos.net_50bhu-512x656.png',
    // 'Atalanta BC': 'https://brandlogos.net/wp-content/uploads/2014/12/atalanta_bc-logo_brandlogos.net_yq22a-512x839.png',
    // 'Bologna FC 1909': 'https://brandlogos.net/wp-content/uploads/2014/12/bologna_FC_1909-logo_brandlogos.net_vf54h-512x744.png',
    // 'Cagliari Calcio': 'https://brandlogos.net/wp-content/uploads/2021/08/cagliari-calcio-logo-512x512.png',
    // 'Como 1907': 'https://brandlogos.net/wp-content/uploads/2025/02/como_1907-logo_brandlogos.net_ehxi8-512x529.png',
    // 'FC Empoli': 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fb/Empoli_FC_crest.svg/269px-Empoli_FC_crest.svg.png?20250118000953',
    // 'Genoa CFC': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2c/Genoa_CFC_crest.svg/800px-Genoa_CFC_crest.svg.png',
    // 'Hellas Verona': 'https://upload.wikimedia.org/wikipedia/en/thumb/9/92/Hellas_Verona_FC_logo_%282020%29.svg/800px-Hellas_Verona_FC_logo_%282020%29.svg.png',
    // 'Inter Milan': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/512px-FC_Internazionale_Milano_2021.svg.png',
    // 'Parma Calcio 1913': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Logo_Parma_Calcio_1913_%28adozione_2016%29.svg/800px-Logo_Parma_Calcio_1913_%28adozione_2016%29.svg.png',
    // 'SS Lazio': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/S.S._Lazio_badge.svg/1024px-S.S._Lazio_badge.svg.png',
    // 'SSC Napoli': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/SSC_Napoli_2024_%28deep_blue_navy%29.svg/800px-SSC_Napoli_2024_%28deep_blue_navy%29.svg.png',
    // 'Torino FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/Torino_FC_Logo.svg/800px-Torino_FC_Logo.svg.png',
    // 'Udinese Calcio': 'https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Udinese_Calcio_logo.svg/800px-Udinese_Calcio_logo.svg.png',
    // 'US Lecce': 'https://upload.wikimedia.org/wikipedia/en/thumb/2/23/US_Lecce_crest.svg/800px-US_Lecce_crest.svg.png',
    // 'Venezia FC': 'https://upload.wikimedia.org/wikipedia/en/thumb/3/39/Venezia_FC_crest.svg/800px-Venezia_FC_crest.svg.png',


    "Arema FC": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Arema_FC_2017_logo.svg/800px-Arema_FC_2017_logo.svg.png",
    "Bali United FC": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Bali_United_logo.svg/200px-Bali_United_logo.svg.png",
    "Bhayangkara Presisi FC": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6a/Bhayangkara_FC_logo.svg/329px-Bhayangkara_FC_logo.svg.png",
    "Borneo FC Samarinda": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Borneo_FC_logo_%282021%29.svg/233px-Borneo_FC_logo_%282021%29.svg.png?20210426035439",
    "Deltras FC": "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Deltras_FC_logo.png/220px-Deltras_FC_logo.png",
    "Dewa United FC": "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Dewa_United_F.C._logo.svg/320px-Dewa_United_F.C._logo.svg.png",
    "Madura United FC": "https://upload.wikimedia.org/wikipedia/en/9/9d/Madura_United_F.C._logo.png",
    "Malut United FC": "https://upload.wikimedia.org/wikipedia/commons/5/53/Malut_United_Football_Club.png",
    "Persebaya Surabaya": "https://upload.wikimedia.org/wikipedia/id/thumb/a/a1/Persebaya_logo.svg/391px-Persebaya_logo.svg.png",
    "Persela Lamongan": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Persela_logo.svg/389px-Persela_logo.svg.png",
    "PERSIB Bandung": "https://upload.wikimedia.org/wikipedia/en/8/85/Persib_Bandung_Football_Logo.png",
    "Persibo Bojonegoro": "https://upload.wikimedia.org/wikipedia/en/c/cb/Persibo.jpeg",
    "Persija Jakarta": "https://upload.wikimedia.org/wikipedia/id/9/94/Persija_Jakarta_logo.png",
    "Persijap Jepara": "https://upload.wikimedia.org/wikipedia/en/b/bc/Persijap.png",
    "Persik Kediri": "https://upload.wikimedia.org/wikipedia/id/c/cd/Logo_Persik_Kediri.png",
    "Persikabo 1973": "https://upload.wikimedia.org/wikipedia/en/c/c9/Persikabo_1973_new_logo.png",
    "Persipura Jayapura": "https://upload.wikimedia.org/wikipedia/en/thumb/6/60/Persipura_logo.svg/427px-Persipura_logo.svg.png",
    "Persiraja Banda Aceh": "https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/Persiraja_logo.svg/480px-Persiraja_logo.svg.png",
    "PERSIS Solo": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/Persis_Solo_logo.svg/356px-Persis_Solo_logo.svg.png",
    "Persita Tangerang": "https://upload.wikimedia.org/wikipedia/id/thumb/9/95/Persita_logo_%282020%29.svg/400px-Persita_logo_%282020%29.svg.png",
    "PS Barito Putera": "https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Barito_Putera_logo-en.svg/461px-Barito_Putera_logo-en.svg.png",
    "PSBS Biak": "https://upload.wikimedia.org/wikipedia/id/9/9b/Logo_PSBS_Biak_baru.png",
    "PSIM Yogyakarta": "https://tmssl.akamaized.net//images/wappen/head/70596.png?lm=1550315068",
    "PSIS Semarang": "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/PSIS_Logo_with_1_star.svg/250px-PSIS_Logo_with_1_star.svg.png",
    "PSKC Cimahi": "https://upload.wikimedia.org/wikipedia/en/9/90/PSKC_badge.jpg",
    "PSM Makassar": "https://upload.wikimedia.org/wikipedia/en/thumb/4/43/PSM_Makassar_logo.svg/422px-PSM_Makassar_logo.svg.png",
    "PSMS Medan": "https://upload.wikimedia.org/wikipedia/en/6/66/PSMS.png",
    "PSPS Pekanbaru": "https://upload.wikimedia.org/wikipedia/en/9/91/Pspsriau.jpeg",
    "PSS Sleman": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/PSS_Sleman_logo.svg/401px-PSS_Sleman_logo.svg.png",
    "RANS Nusantara FC": "https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/RANS_Cilegon_F.C._logo.svg/480px-RANS_Cilegon_F.C._logo.svg.png",
    "Semen Padang FC": "https://upload.wikimedia.org/wikipedia/id/1/1e/Semen_Padang_FC.png",
    "Sriwijaya FC": "https://upload.wikimedia.org/wikipedia/en/thumb/9/93/Sriwijaya_FC_logo.svg/306px-Sriwijaya_FC_logo.svg.png",

    "AJ Auxerre": "https://upload.wikimedia.org/wikipedia/en/thumb/5/51/AJAuxerreLogo.svg/380px-AJAuxerreLogo.svg.png",
    "Angers SCO": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Angers_SCO_logo.svg/402px-Angers_SCO_logo.svg.png",
    "AS Monaco": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/LogoASMonacoFC2021.svg/277px-LogoASMonacoFC2021.svg.png",
    "AS Saint-Étienne": "https://upload.wikimedia.org/wikipedia/en/thumb/2/25/AS_Saint-%C3%89tienne_logo.svg/385px-AS_Saint-%C3%89tienne_logo.svg.png",
    "FC Nantes": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Logo_FC_Nantes_%28avec_fond%29_-_2019.svg/372px-Logo_FC_Nantes_%28avec_fond%29_-_2019.svg.png",
    "FC Toulouse": "https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Toulouse_FC_2018_logo.svg/480px-Toulouse_FC_2018_logo.svg.png",
    "Le Havre AC": "https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Le_Havre_AC_logo.svg/395px-Le_Havre_AC_logo.svg.png",
    "LOSC Lille": "https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Lille_OSC_2018_logo.svg/505px-Lille_OSC_2018_logo.svg.png",
    "Montpellier HSC": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a8/Montpellier_HSC_logo.svg/480px-Montpellier_HSC_logo.svg.png",
    "OGC Nice": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/OGC_Nice_logo.svg/389px-OGC_Nice_logo.svg.png",
    "Olympique Lyon": "https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/Olympique_Lyonnais_logo.svg/412px-Olympique_Lyonnais_logo.svg.png",
    "Olympique Marseille": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Olympique_Marseille_logo.svg/371px-Olympique_Marseille_logo.svg.png",
    "Paris Saint-Germain": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/480px-Paris_Saint-Germain_F.C..svg.png",
    "RC Lens": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/RC_Lens_logo.svg/357px-RC_Lens_logo.svg.png",
    "RC Strasbourg Alsace": "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Racing_Club_de_Strasbourg_logo.svg/480px-Racing_Club_de_Strasbourg_logo.svg.png",
    "Stade Brestois 29": "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Stade_Brestois_29_logo.svg/396px-Stade_Brestois_29_logo.svg.png",
    "Stade Reims": "https://upload.wikimedia.org/wikipedia/en/thumb/1/19/Stade_de_Reims_logo.svg/242px-Stade_de_Reims_logo.svg.png",
    "Stade Rennais FC": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Stade_Rennais_FC.svg/435px-Stade_Rennais_FC.svg.png",

    "AFC Bournemouth": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/AFC_Bournemouth_%282013%29.svg/365px-AFC_Bournemouth_%282013%29.svg.png",
    "Arsenal FC": "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/409px-Arsenal_FC.svg.png",
    "Aston Villa": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Aston_Villa_FC_new_crest.svg/355px-Aston_Villa_FC_new_crest.svg.png",
    "Brentford FC": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/480px-Brentford_FC_crest.svg.png",
    "Brighton & Hove Albion": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Brighton_and_Hove_Albion_FC_crest.svg/480px-Brighton_and_Hove_Albion_FC_crest.svg.png",
    "Chelsea FC": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/480px-Chelsea_FC.svg.png",
    "Crystal Palace": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Crystal_Palace_FC_logo_%282022%29.svg/385px-Crystal_Palace_FC_logo_%282022%29.svg.png",
    "Everton FC": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/469px-Everton_FC_logo.svg.png",
    "Fulham FC": "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Fulham_FC_%28shield%29.svg/360px-Fulham_FC_%28shield%29.svg.png",
    "Ipswich Town": "https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Ipswich_Town.svg/385px-Ipswich_Town.svg.png",
    "Leicester City": "https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/Leicester_City_crest.svg/480px-Leicester_City_crest.svg.png",
    "Liverpool FC": "https://brandlogos.net/wp-content/uploads/2025/02/liverpool_f.c.-logo_brandlogos.net_vr9dx-512x936.png",
    "Manchester City": "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/480px-Manchester_City_FC_badge.svg.png",
    "Manchester United": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/474px-Manchester_United_FC_crest.svg.png",
    "Newcastle United": "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/477px-Newcastle_United_Logo.svg.png",
    "Nottingham Forest": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Nottingham_Forest_F.C._logo.svg/225px-Nottingham_Forest_F.C._logo.svg.png",
    "Southampton FC": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/FC_Southampton.svg/420px-FC_Southampton.svg.png",
    "Tottenham Hotspur": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/234px-Tottenham_Hotspur.svg.png",
    "West Ham United": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/West_Ham_United_FC_logo.svg/431px-West_Ham_United_FC_logo.svg.png",
    "Wolverhampton Wanderers": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Wolverhampton_Wanderers_FC_crest.svg/555px-Wolverhampton_Wanderers_FC_crest.svg.png",

    "1.FC Heidenheim 1846": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/1._FC_Heidenheim_1846.svg/389px-1._FC_Heidenheim_1846.svg.png",
    "1.FC Union Berlin": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/1._FC_Union_Berlin_Logo.svg/640px-1._FC_Union_Berlin_Logo.svg.png",
    "1.FSV Mainz 05": "https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Mainz_05_crest.svg/516px-Mainz_05_crest.svg.png",
    "Bayern Munich": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg/500px-FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg.png",
    "Bayer 04 Leverkusen": "https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Bayer_04_Leverkusen_logo.svg/620px-Bayer_04_Leverkusen_logo.svg.png",
    "Borussia Dortmund": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/500px-Borussia_Dortmund_logo.svg.png",
    "Borussia Mönchengladbach": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Borussia_M%C3%B6nchengladbach_logo.svg/301px-Borussia_M%C3%B6nchengladbach_logo.svg.png",
    "Eintracht Frankfurt": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Eintracht_Frankfurt_crest.svg/480px-Eintracht_Frankfurt_crest.svg.png",
    "FC Augsburg": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/FC_Augsburg_logo.svg/368px-FC_Augsburg_logo.svg.png",
    "FC St. Pauli": "https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/FC_St._Pauli_logo_%282018%29.svg/480px-FC_St._Pauli_logo_%282018%29.svg.png",
    "Holstein Kiel": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Holstein_Kiel_Logo.svg/480px-Holstein_Kiel_Logo.svg.png",
    "RB Leipzig": "https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/640px-RB_Leipzig_2014_logo.svg.png",
    "SC Freiburg": "https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/SC_Freiburg_logo.svg/342px-SC_Freiburg_logo.svg.png",
    "SV Werder Bremen": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/SV-Werder-Bremen-Logo.svg/319px-SV-Werder-Bremen-Logo.svg.png",
    "TSG 1899 Hoffenheim": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Logo_TSG_Hoffenheim.svg/500px-Logo_TSG_Hoffenheim.svg.png",
    "VfB Stuttgart": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/VfB_Stuttgart_1893_Logo.svg/441px-VfB_Stuttgart_1893_Logo.svg.png",
    "VfL Bochum": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/VfL_Bochum_logo.svg/456px-VfL_Bochum_logo.svg.png",
    "VfL Wolfsburg": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/VfL_Wolfsburg_Logo.svg/480px-VfL_Wolfsburg_Logo.svg.png",

    "Athletic Bilbao": "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Club_Athletic_Bilbao_logo.svg/423px-Club_Athletic_Bilbao_logo.svg.png",
    "Atlético de Madrid": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Atletico_Madrid_Logo_2024.svg/374px-Atletico_Madrid_Logo_2024.svg.png",
    "CA Osasuna": "https://upload.wikimedia.org/wikipedia/en/thumb/3/38/CA_Osasuna_2024_crest.svg/358px-CA_Osasuna_2024_crest.svg.png",
    "CD Leganés": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/Club_Deportivo_Legan%C3%A9s_logo.svg/490px-Club_Deportivo_Legan%C3%A9s_logo.svg.png",
    "Celta de Vigo": "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/RC_Celta_de_Vigo_logo.svg/270px-RC_Celta_de_Vigo_logo.svg.png",
    "Deportivo Alavés": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Deportivo_Alaves_logo_%282020%29.svg/482px-Deportivo_Alaves_logo_%282020%29.svg.png",
    "FC Barcelona": "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/473px-FC_Barcelona_%28crest%29.svg.png",
    "Getafe CF": "https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Getafe_logo.svg/459px-Getafe_logo.svg.png",
    "Girona FC": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Girona_FC_Logo.svg/480px-Girona_FC_Logo.svg.png",
    "Rayo Vallecano": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d8/Rayo_Vallecano_logo.svg/540px-Rayo_Vallecano_logo.svg.png",
    "RCD Espanyol Barcelona": "https://upload.wikimedia.org/wikipedia/en/thumb/9/92/RCD_Espanyol_crest.svg/339px-RCD_Espanyol_crest.svg.png",
    "RCD Mallorca": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Rcd_mallorca.svg/362px-Rcd_mallorca.svg.png",
    "Real Betis Balompié": "https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_betis_logo.svg/585px-Real_betis_logo.svg.png",
    "Real Madrid": "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/357px-Real_Madrid_CF.svg.png",
    "Real Sociedad": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Real_Sociedad_logo.svg/418px-Real_Sociedad_logo.svg.png",
    "Real Valladolid CF": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Real_Valladolid_CF_crest.svg/427px-Real_Valladolid_CF_crest.svg.png",
    "Sevilla FC": "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Sevilla_FC_logo.svg/395px-Sevilla_FC_logo.svg.png",
    "UD Las Palmas": "https://upload.wikimedia.org/wikipedia/en/thumb/2/20/UD_Las_Palmas_logo.svg/278px-UD_Las_Palmas_logo.svg.png",
    "Valencia CF": "https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/Valenciacf.svg/381px-Valenciacf.svg.png",
    "Villarreal CF": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Villarreal_CF_logo-en.svg/385px-Villarreal_CF_logo-en.svg.png"

};

export const getLogoCode = (clubCode: string): string => {
    return clubLogoCodeMap[clubCode] || ''; // Kode negara tidak valid
};